{{ if .Values.schema.enabled | default false }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.appName }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: public.ecr.aws/w8x4g9h7/roboshop-v3/schema-load
          env:
          {{- range .Values.SCHEMA_FILES }}
          - name: SCHEMA_FILES
            value: {{ . | quote }}

          envFrom:
            - configMapRef:
                name: {{ $.Values.appName }}
          {{- end }}
      restartPolicy: Never
  backoffLimit: 0
  {{ end }}