apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    appName: {{ .Values.appName }}
  ports:
{{- if eq .Values.appName "frontend" }}
   - port: 9113 # Service port
     targetPort: 9113
     name: metrics
{{- end }}
    - port: {{ .Values.port }} # Service port
      targetPort: {{ .Values.port }}  # Pod container port
      name: default
  type: {{ .Values.service.type }} # by default cluster ip
