apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    appName: {{ .Values.appName }}
  ports:
    - port: {{ .Values.port }} # Service port
      targetPort: {{ .Values.port }}  # Pod container port
  type: ClusterIP # by default cluster ip